import cv2
import numpy as np


def check_fft(frames):
    """
    Signal 6 — FFT Frequency Domain Analysis.

    Deepfakes generated by neural networks leave characteristic artifacts in
    the frequency domain — specifically a lack of high-frequency texture detail
    and unnatural spectral distribution that is invisible to the human eye but
    statistically detectable.

    Method:
    - Convert each frame to grayscale
    - Apply 2D FFT and shift zero-frequency to centre
    - Compute log-magnitude spectrum
    - Measure the ratio of high-frequency energy to total energy
    - Deepfakes have suppressed high-frequency content (low ratio)
    - Also check spectral flatness — deepfakes show unnaturally flat spectra

    Triggered if:
      - avg high-freq ratio < 0.35  (suppressed texture detail)
      OR
      - spectral flatness std across frames < 0.01 (unnaturally uniform spectrum)
    """
    if not frames:
        return {
            "score": 0,
            "triggered": False,
            "available": True,
            "explanation": "No frames available for frequency analysis.",
        }

    hf_ratios = []
    flatness_values = []

    for frame in frames:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY).astype(np.float32)

        # 2D FFT
        fft = np.fft.fft2(gray)
        fft_shift = np.fft.fftshift(fft)
        magnitude = np.log1p(np.abs(fft_shift))

        h, w = magnitude.shape
        cy, cx = h // 2, w // 2

        # High-frequency ring = outer 60% of spectrum radius
        y_idx, x_idx = np.ogrid[:h, :w]
        dist = np.sqrt((y_idx - cy) ** 2 + (x_idx - cx) ** 2)
        max_dist = np.sqrt(cy ** 2 + cx ** 2)

        total_energy = np.sum(magnitude)
        hf_mask = dist > 0.4 * max_dist
        hf_energy = np.sum(magnitude[hf_mask])

        hf_ratio = float(hf_energy / total_energy) if total_energy > 0 else 0
        hf_ratios.append(hf_ratio)

        # Spectral flatness (geometric mean / arithmetic mean of magnitude)
        flat_vals = magnitude[magnitude > 0]
        if len(flat_vals) > 0:
            geo_mean = np.exp(np.mean(np.log(flat_vals + 1e-10)))
            arith_mean = np.mean(flat_vals)
            flatness = float(geo_mean / arith_mean) if arith_mean > 0 else 0
            flatness_values.append(flatness)

    avg_hf_ratio = float(np.mean(hf_ratios)) if hf_ratios else 0
    flatness_std = float(np.std(flatness_values)) if len(flatness_values) > 1 else 1.0

    # Calibrated threshold: real videos and modern deepfakes both show hf_ratio ~0.65.
    # The flatness_std trigger was removed — it fired on ALL video types equally (useless).
    # Only keep the low-hf trigger with a raised threshold to avoid false positives.
    low_hf = avg_hf_ratio < 0.55

    triggered = bool(low_hf)

    if triggered:
        explanation = (
            f"Suppressed high-frequency content (ratio={round(avg_hf_ratio, 3)}) — "
            "neural network generators smooth out fine texture detail invisible to the human eye."
        )
    else:
        explanation = (
            f"Frequency spectrum appears natural "
            f"(high-freq ratio={round(avg_hf_ratio, 3)}, spectral variance={round(flatness_std, 4)})."
        )

    return {
        "score": 25 if triggered else 0,
        "triggered": triggered,
        "available": True,
        "avg_hf_ratio": round(avg_hf_ratio, 4),
        "flatness_std": round(flatness_std, 5),
        "explanation": explanation,
    }
