// frontend/src/app/components/HistoryView.jsx
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader } from "@/app/components/ui/card";
import { Button } from "@/app/components/ui/button";
import { ChevronDown, ChevronUp, Download, Clock, Film } from "lucide-react";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:5000";

const VERDICT_STYLE = {
  DEEPFAKE:     "bg-red-500/20 text-red-400 border border-red-500/40",
  AUTHENTIC:    "bg-green-500/20 text-green-400 border border-green-500/40",
  INCONCLUSIVE: "bg-yellow-500/20 text-yellow-400 border border-yellow-500/40",
};

function downloadReport(item) {
  const report = [
    "FRAUDA — AI TRUST INTELLIGENCE",
    "Analysis Report",
    "=".repeat(40),
    `Analysis ID    : ${item.id}`,
    `Video Name     : ${item.video_name}`,
    `Verdict        : ${item.verdict}`,
    `AI Score       : ${item.ai_score}`,
    `Confidence     : ${item.confidence_score}%`,
    `Risk Level     : ${item.risk_level}`,
    `Frames Analyzed: ${item.frames_analyzed}`,
    `Timestamp      : ${new Date(item.created_at).toLocaleString()}`,
    "",
    "Detection Reasons:",
    ...(item.reasons || []).map((r) => `  • ${r}`),
    "",
    "Explanation:",
    item.explanation || "N/A",
    "",
    "=".repeat(40),
    "Generated by Frauda — AI Trust Intelligence",
    "Hackathon 2026 | Team AF (Aurea Fabrica)",
  ].join("\n");

  const blob = new Blob([report], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `frauda_report_${(item.id || "report").slice(0, 8)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function HistoryItem({ item }) {
  const [expanded, setExpanded] = useState(false);
  const verdictStyle = VERDICT_STYLE[item.verdict] || VERDICT_STYLE.INCONCLUSIVE;

  return (
    <Card className="bg-slate-900/60 border border-slate-700/50 hover:border-blue-500/40 transition-all duration-200">
      <CardHeader
        className="cursor-pointer select-none p-4"
        onClick={() => setExpanded((v) => !v)}
      >
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3 min-w-0">
            <Film size={16} className="text-blue-400 shrink-0" />
            <span className="font-mono text-sm text-white truncate max-w-[200px] sm:max-w-[320px]">
              {item.video_name}
            </span>
            <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${verdictStyle}`}>
              {item.verdict}
            </span>
          </div>
          <div className="flex items-center gap-3 text-xs text-slate-400">
            <Clock size={12} />
            {new Date(item.created_at).toLocaleDateString("en-MY", {
              day: "2-digit", month: "short", year: "numeric",
              hour: "2-digit", minute: "2-digit",
            })}
            {expanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
          </div>
        </div>
      </CardHeader>

      {expanded && (
        <CardContent className="px-4 pb-4 border-t border-slate-700/50 pt-4 space-y-4">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: "AI Score",   value: `${item.ai_score ?? "—"}` },
              { label: "Confidence", value: `${item.confidence_score ?? "—"}%` },
              { label: "Risk Level", value: item.risk_level ?? "—" },
              { label: "Frames",     value: item.frames_analyzed ?? "—" },
            ].map(({ label, value }) => (
              <div key={label} className="bg-slate-800/60 rounded-lg p-3 text-center">
                <p className="text-xs text-slate-400 mb-1">{label}</p>
                <p className="text-sm font-bold text-white">{value}</p>
              </div>
            ))}
          </div>

          {item.reasons?.length > 0 && (
            <div>
              <p className="text-xs text-slate-400 mb-2 uppercase tracking-wider">
                Detection Signals
              </p>
              <ul className="space-y-1">
                {item.reasons.map((r, i) => (
                  <li key={i} className="text-xs text-slate-300 flex gap-2">
                    <span className="text-red-400">▸</span> {r}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {item.explanation && (
            <div>
              <p className="text-xs text-slate-400 mb-1 uppercase tracking-wider">Explanation</p>
              <p className="text-xs text-slate-300 leading-relaxed">{item.explanation}</p>
            </div>
          )}

          <Button
            size="sm"
            variant="outline"
            className="border-blue-500/40 text-blue-400 hover:bg-blue-500/10 text-xs"
            onClick={() => downloadReport(item)}
          >
            <Download size={12} className="mr-1.5" />
            Download Report
          </Button>
        </CardContent>
      )}
    </Card>
  );
}

export default function HistoryView() {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);

  useEffect(() => {
    fetch(`${API_BASE}/history`)
      .then((r) => r.json())
      .then((d) => {
        if (d.status === "success") setHistory(d.data);
        else setError("Failed to load history.");
      })
      .catch(() => setError("Cannot reach server."))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-3 max-w-3xl mx-auto">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-white">Analysis History</h2>
        <span className="text-xs text-slate-400">
          {history.length} record{history.length !== 1 ? "s" : ""}
        </span>
      </div>

      {loading && (
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-16 rounded-xl bg-slate-800/50 animate-pulse" />
          ))}
        </div>
      )}

      {error && (
        <div className="text-center py-12 text-slate-400">
          <p className="text-sm">{error}</p>
        </div>
      )}

      {!loading && !error && history.length === 0 && (
        <div className="text-center py-16 text-slate-500">
          <Film size={32} className="mx-auto mb-3 opacity-40" />
          <p className="text-sm">No analyses yet. Upload a video to get started.</p>
        </div>
      )}

      {history.map((item) => (
        <HistoryItem key={item.id} item={item} />
      ))}
    </div>
  );
}
